### ISSUE TITLE
Shipping classes compatibility with WPML WooCommerce

### ISSUE THREAD

**Issue by martynaskre** [mijora/omniva-woocommerce#162]
If [WPML WooCommerce](https://wpml.org/documentation/related-projects/woocommerce-multilingual/) plugin is installed with WPML, shipping classes select appears as empty (e.g. shown below) because WPML WooCommerce tries to translate these taxonomies.

![Screenshot 2023-03-23 at 23 52 16](https://user-images.githubusercontent.com/10911957/227372729-3d07881d-5fc4-4e27-b84e-cf3b366befe6.png)

Furthermore, it is not recommended to query shipping classes directly using [get_terms](https://github.com/mijora/omniva-woocommerce/blob/master/omniva-woocommerce/core/class-shipping-method.php#L1220) as it bypasses the `woocommerce_get_shipping_classes` filter applied by WooCommerce. This results in shipping classes that are not **cached** and not **filtered**, leading to poor behaviour. Instead, shipping classes should be queried using `WC()->shipping()->get_shipping_classes()` or any other method that provides the same functionality.

**Comment by markakk** [comment]
Hello,

We recommend to disable the translation of shipping classes, because this is a system parameter and is not visible to buyers, so its translation is not necessary. This will avoid problems not only in Omniva, but also in other plugins.
![image](https://user-images.githubusercontent.com/71830881/233375172-5928ac51-2e93-4532-bd36-c25995e764e1.png)
If the translation of the shipping classes is required, then write the problem to us by e-mail omniva@mijora.lt, so that we can agree on the possibility to check this problem on your website.
